### ISSUE TITLE
Sample State suggestions

### ISSUE THREAD

**Issue by brtrick** [josephwyang/accord#3]
Great job with the sample state! A couple comments:
1. accordTag seems to become accord after the first user.
2. Under memberships, which memberships do you plan to load? Current user and the current user's servers? Just curious because you label the one as the membership for eric#0016, but would it be better to say membership for server #29? (The state looks fine, just curious about this point.)     

Otherwise, looks good!

**Comment by josephwyang** [comment]
1. That's insane that you caught that! Just fixed it!
2. Oh yes I totally see what you're saying. But yeah that is what I wanted—to show the memberships that the current user has to their servers, but also all the memberships that each of those servers have (to display the server members on the right when navigating within a server). But yes, I think what your suggestion makes more sense! Just updated it to reflect that it was the memberships for the server, not the user.  Also updated all of them not to have that image_url that you informed me that I would need!\

Thank you again Brad!

**Comment by brtrick** [comment]
I think you do want the image_urls in state, just not in your db. 😁

**Comment by josephwyang** [comment]
Oh! Okay I'll add them back in then hahah, also a side question, but do I want to close these issues myself?

**Comment by brtrick** [comment]
Don't worry about closing them. I'll go back through once I've finished the initial pass and close them.

**Comment by brtrick** [comment]
Looks good. Closing the issue.
