### ISSUE TITLE
MVP #2 Review: User Auth & Splash Page

### ISSUE THREAD

**Issue by josephwyang** [josephwyang/accord#6]
Thank you Brad!

**Comment by brtrick** [comment]
Overall, looks great! Couple comments:

Splash page:
- [ ] Add another panel or two so you can scroll

Auth:
- [ ] How do I logout?
- [ ] When I login as a user I just created, it shows me the server index on the side and the rest of the page is blank. (I tried creating a server after sign up, so maybe that is part of the problem.)
